version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - 27017:27017
    volumes:
        - ./data/mongo:/data/db
        - ./data/mongo/config:/data/config
        - ./data/mongo/logs:/data/logs
    env_file:
      - ./.env

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/
    env_file:
      - ./.env

  fbw-bot:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: fbw-bot
    restart: always
    ports:
      - 3000:3000
    env_file:
      - ./.env
