blank_issues_enabled: false
contact_links:
  - name: FBW Bot channel on Discord
    url: https://discord.com/channels/738864299392630914/897491699167793182
    about: Discuss the FBW Discord bot on its own Discord Channel
